- name: This playbook will install nginx, configures nginx to pick html from custom directory and deploy custom html web page
  hosts: all
  tasks:
  - name: Install nginx in Ubuntu ansible node
    apt: name=nginx state=latest update_cache=yes

  - name: Start nginx web server in Ubuntu ansible node
    shell: service nginx start

  - name: Create the custom web root folder
    file: path=/var/html state=directory mode=0777

  - name: Configure nginx web serve to serve web pages from our custom folder 
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx web server in Ubuntu ansible node to apply the config changes
    shell: service nginx restart

  - name: Deploy custom web page into nginx web server on Ubuntu ansible node
    copy: src=index.html dest=/var/html/index.html


